[package]
name = "apk-patcher-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { version = "7.1.3", features = ["docsrs"] }
zip = { version = "0.6.4", default-features = false, features = ["deflate"] }
